### ISSUE TITLE
Will bits and pieces from NPE be added as well?

### ISSUE THREAD

**Issue by xplshn** [staalmannen/APExp#3]

**Comment by staalmannen** [comment]
I am very interested in adding the SDL compatibility stuff they have managed to do. The alternative might be to try to build a port of SDL2. Also, it might be interesting to evaluate their pthread implementation compared to the one I imported from lufia's patch.

Basically, since this is a free-standing APE, we are free to "go fast and break things" and I am very open to integrate any experimental patches and 3rd party libraries that help towards the overall aim : a low threshold to build 3rd party applications (preferably just configure/make like on any *nix). I found a couple of blocking issues for the configure script, which got resolved by building sbase ls and cat - this will end up in the next commit (in the process of updating gawk)
